package gui;

import javax.swing.JOptionPane;

public class DialogoCrearMesa extends javax.swing.JDialog {

    public static int ACEPTADO = 0;
    public static int CANCELADO = 1;
    
    public static int HOLDEM = 0;
    public static int FIVECARDS = 1;
    public static int OMAHA = 2;
    
    public int estado;
    public int juego;
    
    public DialogoCrearMesa(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        this.estado = DialogoCrearMesa.CANCELADO;
        this.juego = DialogoCrearMesa.HOLDEM;
    }
    
    private String validarDatos()
    {
        if (this.nombreMesa.getText().isEmpty())
        {
            return "Ingrese un nombre para la mesa.";
        }
        return null;
    }
    
    public String getNombreMesa()
    {
        return this.nombreMesa.getText();
    }
    
    public int getMaxJugadores()
    {
        return (int) this.cantidadJugadores.getValue();
    }
    
    public int getTipoJuego()
    {
        return this.juego;
    }
    
    public int getEstado()
    {
        return this.estado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoJuego = new javax.swing.ButtonGroup();
        nombreMesa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cantidadJugadores = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        holdemButton = new javax.swing.JRadioButton();
        fiveCardsButton = new javax.swing.JRadioButton();
        omahaButton = new javax.swing.JRadioButton();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setLabelFor(nombreMesa);
        jLabel1.setText("Nombre");

        jLabel2.setLabelFor(cantidadJugadores);
        jLabel2.setText("Cantidad Máxima de Jugadores");

        cantidadJugadores.setModel(new javax.swing.SpinnerNumberModel(3, 2, 5, 1));

        jLabel3.setText("Tipo de Juego");

        tipoJuego.add(holdemButton);
        holdemButton.setSelected(true);
        holdemButton.setText("Texas Holdem");
        holdemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holdemButtonActionPerformed(evt);
            }
        });

        tipoJuego.add(fiveCardsButton);
        fiveCardsButton.setText("Five Cards");
        fiveCardsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveCardsButtonActionPerformed(evt);
            }
        });

        tipoJuego.add(omahaButton);
        omahaButton.setText("Omaha");
        omahaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                omahaButtonActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(botonCancelar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonAceptar)
                    .addComponent(omahaButton))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nombreMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cantidadJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(holdemButton)
                        .addGap(18, 18, 18)
                        .addComponent(fiveCardsButton))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidadJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fiveCardsButton)
                    .addComponent(holdemButton)
                    .addComponent(omahaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.estado = DialogoCrearMesa.CANCELADO;
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        String error = this.validarDatos();
        if (error == null)
        {
            this.estado = DialogoCrearMesa.ACEPTADO;
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, error, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void holdemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holdemButtonActionPerformed
        this.juego = DialogoCrearMesa.HOLDEM;
    }//GEN-LAST:event_holdemButtonActionPerformed

    private void fiveCardsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveCardsButtonActionPerformed
        this.juego = DialogoCrearMesa.FIVECARDS;
    }//GEN-LAST:event_fiveCardsButtonActionPerformed

    private void omahaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_omahaButtonActionPerformed
        this.juego = DialogoCrearMesa.OMAHA;
    }//GEN-LAST:event_omahaButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JSpinner cantidadJugadores;
    private javax.swing.JRadioButton fiveCardsButton;
    private javax.swing.JRadioButton holdemButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nombreMesa;
    private javax.swing.JRadioButton omahaButton;
    private javax.swing.ButtonGroup tipoJuego;
    // End of variables declaration//GEN-END:variables
}
