package gui;

import cliente.Cliente;
import comandos.ComandoIniciarPartidaCliente;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;

public class VentanaEspera extends javax.swing.JFrame {
    
    public VentanaEspera(boolean esCreador)
    {
        initComponents();
        botonIniciar.setEnabled(esCreador);
        botonIniciar.setVisible(esCreador);
        //Se agrega el comando para iniciar la partida con la ventana de espera.
        Cliente.getInstance().getsocketCliente().putComando("iniciarPartida", new ComandoIniciarPartidaCliente(this));
    }
    
    public void establecerNombreMesa(String nombre)
    {
        this.nombreMesa.setText(nombre);
    }
    
    /**
     * Método que crea la ventana de juego cuando el servidor indica el inicio de la partida.
     */
    public void crearVentanaJuego()
    {
        this.setVisible(false);
        VentanaJuego dialog = new VentanaJuego();
        dialog.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreMesa = new javax.swing.JLabel();
        botonIniciar = new javax.swing.JButton();
        spinner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mesa");

        nombreMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreMesa.setText("Nombre de Mesa");

        botonIniciar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botonIniciar.setText("Iniciar");
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });

        spinner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spinner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/spinner.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(botonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreMesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
        List<Object> params = new ArrayList<>();
        params.add(Cliente.getInstance().getidMesa());
        params.add(Cliente.getInstance().getJugador().getId());
        Cliente.getInstance().getsocketCliente().enviarComando("iniciarPartida", params);
    }//GEN-LAST:event_botonIniciarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombreMesa;
    private javax.swing.JLabel spinner;
    // End of variables declaration//GEN-END:variables
}
